spring:
  application:
    name: zuul-api-gateway

server:
  port: 8081

zuul:
  prefix: /api
  #ignoredServices: '*'
  routes:
    product-service:
      path: /product-service/**
#      url: http://localhost:8083
      serviceId: PRODUCT-SERV
    stock-service:
      path: /stock-service/**
#      url: http://localhost:8084
      serviceId: STOCK-SERV
    estimation-service:
      path: /estimation-service/**
#      url: http://localhost:8085
      serviceId: ESTIMATION-SERV
    order-service:
      path: /order-service/**
#      url: http://localhost:8086
      serviceId: ORDER-SERV

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
  instance:
    prefer-ip-address: false
